/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2023, Qualcomm Innovation Center, Inc. All rights reserved.
 * Copyright (c) 2025, Danila Tikhonov <danila@jiaxyga.com>
 */

#ifndef _DT_BINDINGS_CLK_QCOM_CAMCC_SM7635H
#define _DT_BINDINGS_CLK_QCOM_CAMCC_SM7635H

/* CAMCC clocks */
#define CAMCC_PLL0			0
#define CAMCC_PLL0_OUT_EVEN		1
#define CAMCC_PLL0_OUT_ODD		2
#define CAMCC_PLL1			3
#define CAMCC_PLL1_OUT_EVEN		4
#define CAMCC_PLL2			5
#define CAMCC_PLL2_OUT_EVEN		6
#define CAMCC_PLL3			7
#define CAMCC_PLL3_OUT_EVEN		8
#define CAMCC_PLL4			9
#define CAMCC_PLL4_OUT_EVEN		10
#define CAMCC_PLL5			11
#define CAMCC_PLL5_OUT_EVEN		12
#define CAMCC_PLL6			13
#define CAMCC_PLL6_OUT_EVEN		14
#define CAMCC_BPS_AHB_CLK		15
#define CAMCC_BPS_AREG_CLK		16
#define CAMCC_BPS_CLK			17
#define CAMCC_BPS_CLK_SRC		18
#define CAMCC_CAMNOC_ATB_CLK		19
#define CAMCC_CAMNOC_AXI_CLK_SRC	20
#define CAMCC_CAMNOC_AXI_HF_CLK		21
#define CAMCC_CAMNOC_AXI_SF_CLK		22
#define CAMCC_CAMNOC_NRT_AXI_CLK	23
#define CAMCC_CAMNOC_RT_AXI_CLK		24
#define CAMCC_CCI_0_CLK			25
#define CAMCC_CCI_0_CLK_SRC		26
#define CAMCC_CCI_1_CLK			27
#define CAMCC_CCI_1_CLK_SRC		28
#define CAMCC_CORE_AHB_CLK		29
#define CAMCC_CPAS_AHB_CLK		30
#define CAMCC_CPHY_RX_CLK_SRC		31
#define CAMCC_CRE_AHB_CLK		32
#define CAMCC_CRE_CLK			33
#define CAMCC_CRE_CLK_SRC		34
#define CAMCC_CSI0PHYTIMER_CLK		35
#define CAMCC_CSI0PHYTIMER_CLK_SRC	36
#define CAMCC_CSI1PHYTIMER_CLK		37
#define CAMCC_CSI1PHYTIMER_CLK_SRC	38
#define CAMCC_CSI2PHYTIMER_CLK		39
#define CAMCC_CSI2PHYTIMER_CLK_SRC	40
#define CAMCC_CSI3PHYTIMER_CLK		41
#define CAMCC_CSI3PHYTIMER_CLK_SRC	42
#define CAMCC_CSIPHY0_CLK		43
#define CAMCC_CSIPHY1_CLK		44
#define CAMCC_CSIPHY2_CLK		45
#define CAMCC_CSIPHY3_CLK		46
#define CAMCC_FAST_AHB_CLK_SRC		47
#define CAMCC_GDSC_CLK			48
#define CAMCC_ICP_ATB_CLK		49
#define CAMCC_ICP_CLK			50
#define CAMCC_ICP_CLK_SRC		51
#define CAMCC_ICP_CTI_CLK		52
#define CAMCC_ICP_TS_CLK		53
#define CAMCC_MCLK0_CLK			54
#define CAMCC_MCLK0_CLK_SRC		55
#define CAMCC_MCLK1_CLK			56
#define CAMCC_MCLK1_CLK_SRC		57
#define CAMCC_MCLK2_CLK			58
#define CAMCC_MCLK2_CLK_SRC		59
#define CAMCC_MCLK3_CLK			60
#define CAMCC_MCLK3_CLK_SRC		61
#define CAMCC_MCLK4_CLK			62
#define CAMCC_MCLK4_CLK_SRC		63
#define CAMCC_OPE_0_AHB_CLK		64
#define CAMCC_OPE_0_AREG_CLK		65
#define CAMCC_OPE_0_CLK			66
#define CAMCC_OPE_0_CLK_SRC		67
#define CAMCC_SLEEP_CLK			68
#define CAMCC_SLEEP_CLK_SRC		69
#define CAMCC_SLOW_AHB_CLK_SRC		70
#define CAMCC_SOC_AHB_CLK		71
#define CAMCC_SYS_TMR_CLK		72
#define CAMCC_TFE_0_AHB_CLK		73
#define CAMCC_TFE_0_CLK			74
#define CAMCC_TFE_0_CLK_SRC		75
#define CAMCC_TFE_0_CPHY_RX_CLK		76
#define CAMCC_TFE_0_CSID_CLK		77
#define CAMCC_TFE_0_CSID_CLK_SRC	78
#define CAMCC_TFE_1_AHB_CLK		79
#define CAMCC_TFE_1_CLK			80
#define CAMCC_TFE_1_CLK_SRC		81
#define CAMCC_TFE_1_CPHY_RX_CLK		82
#define CAMCC_TFE_1_CSID_CLK		83
#define CAMCC_TFE_1_CSID_CLK_SRC	84
#define CAMCC_TFE_2_AHB_CLK		85
#define CAMCC_TFE_2_CLK			86
#define CAMCC_TFE_2_CLK_SRC		87
#define CAMCC_TFE_2_CPHY_RX_CLK		88
#define CAMCC_TFE_2_CSID_CLK		89
#define CAMCC_TFE_2_CSID_CLK_SRC	90
#define CAMCC_TOP_SHIFT_CLK		91
#define CAMCC_XO_CLK_SRC		92

/* CAMCC resets */
#define CAMCC_BPS_BCR			0
#define CAMCC_CAMNOC_BCR		1
#define CAMCC_CAMSS_TOP_BCR		2
#define CAMCC_CCI_0_BCR			3
#define CAMCC_CCI_1_BCR			4
#define CAMCC_CPAS_BCR			5
#define CAMCC_CRE_BCR			6
#define CAMCC_CSI0PHY_BCR		7
#define CAMCC_CSI1PHY_BCR		8
#define CAMCC_CSI2PHY_BCR		9
#define CAMCC_CSI3PHY_BCR		10
#define CAMCC_ICP_BCR			11
#define CAMCC_MCLK0_BCR			12
#define CAMCC_MCLK1_BCR			13
#define CAMCC_MCLK2_BCR			14
#define CAMCC_MCLK3_BCR			15
#define CAMCC_MCLK4_BCR			16
#define CAMCC_OPE_0_BCR			17
#define CAMCC_TFE_0_BCR			18
#define CAMCC_TFE_1_BCR			19
#define CAMCC_TFE_2_BCR			20

#endif
