/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2023, Qualcomm Innovation Center, Inc. All rights reserved.
 * Copyright (c) 2025, Danila Tikhonov <danila@jiaxyga.com>
 */

#ifndef _DT_BINDINGS_CLK_QCOM_DISPCC_SM7635H
#define _DT_BINDINGS_CLK_QCOM_DISPCC_SM7635H

/* DISPCC clocks */
#define DISPCC_PLL0					0
#define DISPCC_MDSS_ACCU_CLK				1
#define DISPCC_MDSS_AHB1_CLK				2
#define DISPCC_MDSS_AHB_CLK				3
#define DISPCC_MDSS_AHB_CLK_SRC				4
#define DISPCC_MDSS_BYTE0_CLK				5
#define DISPCC_MDSS_BYTE0_CLK_SRC			6
#define DISPCC_MDSS_BYTE0_DIV_CLK_SRC			7
#define DISPCC_MDSS_BYTE0_INTF_CLK			8
#define DISPCC_MDSS_DPTX0_AUX_CLK			9
#define DISPCC_MDSS_DPTX0_AUX_CLK_SRC			10
#define DISPCC_MDSS_DPTX0_CRYPTO_CLK			11
#define DISPCC_MDSS_DPTX0_LINK_CLK			12
#define DISPCC_MDSS_DPTX0_LINK_CLK_SRC			13
#define DISPCC_MDSS_DPTX0_LINK_DIV_CLK_SRC		14
#define DISPCC_MDSS_DPTX0_LINK_INTF_CLK			15
#define DISPCC_MDSS_DPTX0_PIXEL0_CLK			16
#define DISPCC_MDSS_DPTX0_PIXEL0_CLK_SRC		17
#define DISPCC_MDSS_DPTX0_PIXEL1_CLK			18
#define DISPCC_MDSS_DPTX0_PIXEL1_CLK_SRC		19
#define DISPCC_MDSS_DPTX0_USB_ROUTER_LINK_INTF_CLK	20
#define DISPCC_MDSS_ESC0_CLK				21
#define DISPCC_MDSS_ESC0_CLK_SRC			22
#define DISPCC_MDSS_MDP1_CLK				23
#define DISPCC_MDSS_MDP_CLK				24
#define DISPCC_MDSS_MDP_CLK_SRC				25
#define DISPCC_MDSS_MDP_LUT1_CLK			26
#define DISPCC_MDSS_MDP_LUT_CLK				27
#define DISPCC_MDSS_NON_GDSC_AHB_CLK			28
#define DISPCC_MDSS_PCLK0_CLK				29
#define DISPCC_MDSS_PCLK0_CLK_SRC			30
#define DISPCC_MDSS_RSCC_AHB_CLK			31
#define DISPCC_MDSS_RSCC_VSYNC_CLK			32
#define DISPCC_MDSS_VSYNC1_CLK				33
#define DISPCC_MDSS_VSYNC_CLK				34
#define DISPCC_MDSS_VSYNC_CLK_SRC			35
#define DISPCC_SLEEP_CLK				36
#define DISPCC_SLEEP_CLK_SRC				37
#define DISPCC_XO_CLK					38
#define DISPCC_XO_CLK_SRC				39

/* DISPCC resets */
#define DISPCC_MDSS_CORE_BCR				0
#define DISPCC_MDSS_CORE_INT2_BCR			1
#define DISPCC_MDSS_RSCC_BCR				2

#endif
